name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-11

        ocaml-compiler:
          #- 4.08.x
          # - 4.09.x
          # - 4.10.x
          # - 4.11.x
          # - 4.12.x
          #- 4.13.x
          #- 4.14.x
          - 5.0.x

    runs-on: ${{ matrix.os }}

    steps:

      - name: Test
        run: |
          brew install opam
          opam init
